"use client";

import Link from "next/link";
import { Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { getSupabase } from "@/lib/supabase";

type Address = { id: string; label: string | null; full_name: string | null; phone: string | null; country: string; region: string | null; city: string; postal_code: string; address_line: string; address_line_2: string | null; is_default: boolean };
const initial = { label: "常用地址", full_name: "", phone: "", country: "Italy", region: "", city: "", postal_code: "", address_line: "", address_line_2: "", is_default: true };

export default function AccountAddressesPage() {
  const [addresses, setAddresses] = useState<Address[]>([]);
  const [form, setForm] = useState(initial);
  const [userId, setUserId] = useState("");
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);
  const load = async () => { const client = getSupabase(); if (!client) return; const { data } = await client.from("customer_addresses").select("id,label,full_name,phone,country,region,city,postal_code,address_line,address_line_2,is_default").order("is_default", { ascending: false }).order("created_at", { ascending: false }); setAddresses((data ?? []) as Address[]); };
  useEffect(() => { const client = getSupabase(); if (!client) return; void client.auth.getUser().then(({ data }) => { if (data.user) { setUserId(data.user.id); void load(); } }); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!userId || saving) return; setSaving(true); setMessage(""); const client = getSupabase()!; if (form.is_default) await client.from("customer_addresses").update({ is_default: false }).eq("customer_id", userId); const { error } = await client.from("customer_addresses").insert({ ...form, customer_id: userId }); if (error) setMessage("地址保存失败，请检查资料后重试。"); else { setForm(initial); setMessage("地址已保存"); await load(); } setSaving(false); };
  const remove = async (id: string) => { const client = getSupabase(); if (!client || !window.confirm("确定删除这个地址吗？")) return; await client.from("customer_addresses").delete().eq("id", id); await load(); };
  return <main className="account-simple-page"><header className="account-page-head"><p className="section-kicker">MY ACCOUNT</p><h1>地址簿</h1><nav><Link href="/account/orders">订单</Link><Link className="active" href="/account/addresses">地址</Link></nav></header>{!userId ? <div className="catalog-empty"><h2>请先登录</h2><Link className="primary-link" href="/login?next=/account/addresses">登录 / 注册</Link></div> : <div className="address-layout"><section className="address-list">{addresses.length ? addresses.map((address) => <article key={address.id}><div><strong>{address.label || "收货地址"}{address.is_default && <em>默认</em>}</strong><p>{address.full_name} · {address.phone}</p><p>{address.address_line} {address.address_line_2}<br/>{address.postal_code} {address.city} {address.region}<br/>{address.country}</p></div><button onClick={() => void remove(address.id)} aria-label="删除地址"><Trash2 /></button></article>) : <div className="catalog-empty"><h2>还没有保存地址</h2></div>}</section><form className="address-form" onSubmit={save}><h2>添加地址</h2><div className="form-grid"><label>地址名称<input value={form.label} onChange={(event) => setForm({ ...form, label: event.target.value })} /></label><label>收件人 *<input value={form.full_name} onChange={(event) => setForm({ ...form, full_name: event.target.value })} required /></label><label>联系电话 *<input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} required /></label><label>国家 *<input value={form.country} onChange={(event) => setForm({ ...form, country: event.target.value })} required /></label><label>省/大区<input value={form.region} onChange={(event) => setForm({ ...form, region: event.target.value })} /></label><label>城市 *<input value={form.city} onChange={(event) => setForm({ ...form, city: event.target.value })} required /></label><label>邮编 *<input value={form.postal_code} onChange={(event) => setForm({ ...form, postal_code: event.target.value })} required /></label><label>详细地址 *<input value={form.address_line} onChange={(event) => setForm({ ...form, address_line: event.target.value })} required /></label><label>补充地址<input value={form.address_line_2} onChange={(event) => setForm({ ...form, address_line_2: event.target.value })} /></label><label className="checkbox-label"><input type="checkbox" checked={form.is_default} onChange={(event) => setForm({ ...form, is_default: event.target.checked })} /> 设为默认地址</label></div>{message && <p className="form-message">{message}</p>}<button disabled={saving}>{saving ? "正在保存…" : "保存地址"}</button></form></div>}</main>;
}
