"use client";

import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { useCart } from "@/components/cart-provider";
import { useLocale } from "@/components/locale-provider";
import { formatPrice } from "@/lib/store-types";

export default function BagPage() {
  const { locale, href } = useLocale();
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  const copy = locale === "it" ? { title: "La tua borsa", count: "articoli", empty: "La borsa è vuota", emptyBody: "Scopri le novità e scegli colore e taglia.", shop: "Inizia a scegliere", remove: "Rimuovi", summary: "Riepilogo", subtotal: "Subtotale", delivery: "Spedizione", calculated: "Calcolata al checkout", free: "Spedizione gratuita in Italia da €99.", total: "Totale stimato", checkout: "Vai al checkout", note: "Disponibilità e prezzo finale vengono ricontrollati dal server prima dell'ordine." } : locale === "en" ? { title: "Your bag", count: "items", empty: "Your bag is empty", emptyBody: "Explore new arrivals and choose your colour and size.", shop: "Start shopping", remove: "Remove", summary: "Order summary", subtotal: "Subtotal", delivery: "Delivery", calculated: "Calculated at checkout", free: "Free delivery in Italy from €99.", total: "Estimated total", checkout: "Go to checkout", note: "Availability and final prices are rechecked by the server before the order." } : { title: "购物袋", count: "种商品", empty: "购物袋还是空的", emptyBody: "从新品中找到适合你的颜色与尺码。", shop: "开始选购", remove: "移除", summary: "订单摘要", subtotal: "商品小计", delivery: "配送", calculated: "结算时计算", free: "订单满 €99 享意大利境内免运费。", total: "预计总计", checkout: "前往结算", note: "库存和最终价格将在提交订单前由服务器重新确认。" };
  return <main className="bag-page"><div className="bag-heading"><p className="section-kicker">YOUR BAG</p><h1>{copy.title}</h1><span>{items.length} {copy.count}</span></div>{!items.length ? <div className="catalog-empty"><ShoppingBag /><h2>{copy.empty}</h2><p>{copy.emptyBody}</p><Link className="primary-link" href={href("/shop")}>{copy.shop}</Link></div> : <div className="bag-layout"><section className="bag-items">{items.map((item) => <article className="bag-item" key={item.variantId}><Link className="bag-image" href={href(`/product/${item.slug}`)}>{item.image ? <Image src={item.image} alt={item.title} width={240} height={300} /> : <span>N</span>}</Link><div className="bag-copy"><Link href={href(`/product/${item.slug}`)}><h2>{item.title}</h2></Link><p>{item.color} / {item.size}</p><strong>{formatPrice(item.unitPrice)}</strong><div className="quantity"><button onClick={() => updateQuantity(item.variantId, item.quantity - 1)}><Minus /></button><span>{item.quantity}</span><button onClick={() => updateQuantity(item.variantId, item.quantity + 1)}><Plus /></button></div></div><button className="remove-button" onClick={() => removeItem(item.variantId)} aria-label={`${copy.remove} ${item.title}`}><Trash2 /></button></article>)}</section><aside className="order-summary"><h2>{copy.summary}</h2><div><span>{copy.subtotal}</span><strong>{formatPrice(subtotal)}</strong></div><div><span>{copy.delivery}</span><span>{copy.calculated}</span></div><p>{copy.free}</p><div className="summary-total"><span>{copy.total}</span><strong>{formatPrice(subtotal)}</strong></div><Link className="checkout-link" href={href("/checkout")}>{copy.checkout} <ArrowRight /></Link><small>{copy.note}</small></aside></div>}</main>;
}
