"use client";
import { useCallback } from "react";
import Link from "next/link";
import { ArrowRight, Boxes, CircleDollarSign, ClipboardList as ClipboardClock, PackageCheck, ShoppingBag, TrendingUp, TriangleAlert } from "lucide-react";
import { PageHead } from "@/components/shared/page-head";
import { SetupBanner } from "@/components/shared/setup-banner";
import { StatCard } from "@/components/shared/stat-card";
import { EmptyState } from "@/components/shared/empty-state";
import { useSupabaseQuery } from "@/hooks/use-supabase-query";
type Dash={products:number;published:number;pending:number;orders:number;revenue:number;low:number};const EMPTY:Dash={products:0,published:0,pending:0,orders:0,revenue:0,low:0};
export default function AdminDashboard(){const query=useCallback(async(c:any)=>{const today=new Date().toISOString().slice(0,10);const [p,pub,pend,orders,revenue,low]=await Promise.all([c.from("products").select("id",{count:"exact",head:true}).is("deleted_at",null),c.from("products").select("id",{count:"exact",head:true}).eq("status","PUBLISHED"),c.from("products").select("id",{count:"exact",head:true}).in("status",["PENDING_DETAILS","PENDING_IMAGES","PENDING_PRICE","PENDING_REVIEW"]),c.from("orders").select("id",{count:"exact",head:true}).gte("created_at",today),c.from("orders").select("total_amount").gte("created_at",today).not("status","eq","CANCELLED"),c.from("inventory").select("id",{count:"exact",head:true}).lte("quantity_on_hand",5)]);return {data:{products:p.count??0,published:pub.count??0,pending:pend.count??0,orders:orders.count??0,revenue:(revenue.data??[]).reduce((a:number,x:any)=>a+Number(x.total_amount),0),low:low.count??0},error:p.error};},[]);const {data}=useSupabaseQuery<Dash>(query,EMPTY);return <main className="page"><PageHead eyebrow="OPERATIONS OVERVIEW" title="经营概览" subtitle="商品、订单与库存的实时工作台。" action={<Link className="button primary" href="/admin/products/pending"><PackageCheck size={15}/>处理待完善商品</Link>}/><SetupBanner/><section className="stats-grid"><StatCard label="商品总数" value={data.products} note="未归档商品" icon={Boxes}/><StatCard label="已上架商品" value={data.published} note="网店当前可见" icon={ShoppingBag}/><StatCard label="今日订单" value={data.orders} note="按创建时间统计" icon={ClipboardClock}/><StatCard label="今日销售额" value={`€ ${data.revenue.toFixed(2)}`} note="不含已取消订单" icon={CircleDollarSign}/></section><section className="content-grid"><div className="panel"><div className="panel-head"><div><h2>经营趋势</h2><p>接入订单后展示最近 7 天销售额</p></div></div><EmptyState title="等待第一笔销售数据" description="订单创建、取消与发货会自动更新库存并进入经营统计。"/></div><aside className="panel"><div className="panel-head"><div><h2>今日待办</h2><p>优先处理影响上架与销售的问题</p></div></div><div className="panel-body quick-list"><Link className="quick-link" href="/admin/products/pending"><span className="quick-icon"><PackageCheck size={18}/></span><span><b>{data.pending} 个待完善商品</b><span>补全图片、价格与描述</span></span><ArrowRight size={15}/></Link><Link className="quick-link" href="/admin/inventory"><span className="quick-icon"><TriangleAlert size={18}/></span><span><b>{data.low} 个低库存 SKU</b><span>低于或等于预警阈值</span></span><ArrowRight size={15}/></Link><Link className="quick-link" href="/admin/orders"><span className="quick-icon"><TrendingUp size={18}/></span><span><b>订单处理</b><span>付款、拣货、发货与退款</span></span><ArrowRight size={15}/></Link></div></aside></section></main>}
