"use client";
import { ChangeEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, EyeOff, ImagePlus, LoaderCircle, Save, Send, Trash2 } from "lucide-react";
import { PageHead } from "@/components/shared/page-head";
import { SetupBanner } from "@/components/shared/setup-banner";
import { EmptyState } from "@/components/shared/empty-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { getSupabase } from "@/lib/supabase/client";
import { PRODUCT_STATUS } from "@/lib/constants";
import type { TablesUpdate } from "@/types/database";

const tabs=["基础信息","规格与库存","图片管理","价格设置","商品描述","网店设置","操作记录"];
type Product=Record<string,any>;
export default function ProductEdit(){const {id}=useParams<{id:string}>();const [tab,setTab]=useState(0);const [product,setProduct]=useState<Product|null>(null);const [categories,setCategories]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
async function load(){const c=getSupabase();if(!c){setLoading(false);return;}setLoading(true);const [{data,error},{data:cats}]=await Promise.all([c.from("products").select("*,categories(name),brands(name),product_variants(*,colors(name),sizes(name),inventory(*)),product_images(*),online_listings(*)").eq("id",id).single(),c.from("categories").select("id,name").order("name")]);if(error)setMessage(error.message);setProduct(data);setCategories(cats??[]);setLoading(false);}useEffect(()=>{void load();},[id]);
function field(name:string,value:any){setProduct(p=>p?{...p,[name]:value}:p)}
async function save(fields:string[]){const c=getSupabase();if(!c||!product)return;setSaving(true);setMessage("");const payload=Object.fromEntries(fields.map(x=>[x,product[x]??null])) as TablesUpdate<"products">;const {error}=await c.from("products").update(payload).eq("id",id);setMessage(error?error.message:"保存成功");setSaving(false);if(!error)void load();}
async function upload(e:ChangeEvent<HTMLInputElement>){const c=getSupabase(),file=e.target.files?.[0];if(!c||!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setMessage("仅支持 JPG、PNG 或 WebP 图片。");return;}if(file.size>10*1024*1024){setMessage("单张图片不能超过 10MB。");return;}setSaving(true);const ext=file.name.split(".").pop();const imageType=product?.product_images?.length?"DETAIL":"MAIN";const folder=imageType==="MAIN"?"main":"detail";const path=`products/${id}/${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await c.storage.from("product-images").upload(path,file,{contentType:file.type});if(error){setMessage(error.message);setSaving(false);return;}const {data:url}=c.storage.from("product-images").getPublicUrl(path);const {error:dbError}=await c.from("product_images").insert({product_id:id,file_path:path,public_url:url.publicUrl,image_type:imageType,sort_order:product?.product_images?.length??0,is_primary:imageType==="MAIN"});setMessage(dbError?dbError.message:"图片上传成功");setSaving(false);if(!dbError)void load();}
async function removeImage(image:any){const c=getSupabase();if(!c)return;setSaving(true);const {error}=await c.storage.from("product-images").remove([image.file_path]);if(!error)await c.from("product_images").delete().eq("id",image.id);setSaving(false);void load();}
async function publish(){const c=getSupabase();if(!c)return;setSaving(true);const {data,error}=await c.rpc("publish_product",{p_product_id:id});const result=data as {message?:string}|null;setMessage(error?.message??result?.message??"商品已上架");setSaving(false);if(!error)void load();}
async function unpublish(){const c=getSupabase();if(!c)return;setSaving(true);const {data,error}=await c.rpc("unpublish_product",{p_product_id:id});const result=data as {message?:string}|null;setMessage(error?.message??result?.message??"商品已下架");setSaving(false);if(!error)void load();}
async function setOnlineLimit(inventoryId:string,value:number){const c=getSupabase();if(!c)return;setSaving(true);const {data,error}=await c.rpc("set_inventory_online_limit",{p_inventory_id:inventoryId,p_limit:Math.max(0,value)});const result=data as {online_quantity_limit?:number}|null;setMessage(error?.message??`线上可售上限已更新为 ${result?.online_quantity_limit??value}`);setSaving(false);if(!error)void load();}
if(loading)return <main className="page"><div className="empty"><LoaderCircle/></div></main>;
if(!product)return <main className="page"><SetupBanner/><EmptyState title="未找到商品" description="请检查数据库连接或商品是否已归档。"/></main>;
return <main className="page"><PageHead eyebrow="PRODUCT DETAILS" title={product.name||product.style_no} subtitle={`款号 ${product.style_no} · 创建于 ${new Date(product.created_at).toLocaleDateString("zh-CN")}`} action={<Link className="button" href="/admin/products"><ArrowLeft size={15}/>全部商品</Link>}/><SetupBanner/><div style={{marginBottom:15}}><StatusBadge value={product.status} label={(PRODUCT_STATUS as any)[product.status]}/></div><div className="tabs">{tabs.map((x,i)=><button className={`tab ${tab===i?"active":""}`} key={x} onClick={()=>setTab(i)}>{x}</button>)}</div>
{message&&<div className={message.includes("成功")||message.includes("上架")?"notice":"notice warning"}>{message}</div>}
{tab===0&&<section className="form-card"><div className="form-grid"><div className="field"><label>款号</label><input value={product.style_no} disabled/></div><div className="field"><label>商品名称 *</label><input value={product.name??""} onChange={e=>field("name",e.target.value)} placeholder="例如：宽松针织开衫"/></div><div className="field"><label>副标题</label><input value={product.subtitle??""} onChange={e=>field("subtitle",e.target.value)}/></div><div className="field"><label>商品分类 *</label><select value={product.category_id??""} onChange={e=>field("category_id",e.target.value||null)}><option value="">请选择分类</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="field"><label>季节</label><input value={product.season??""} onChange={e=>field("season",e.target.value)}/></div><div className="field"><label>材质</label><input value={product.material??""} onChange={e=>field("material",e.target.value)}/></div><div className="field"><label>产地</label><input value={product.origin??""} onChange={e=>field("origin",e.target.value)}/></div><div className="field full"><label>内部备注</label><textarea value={product.internal_notes??""} onChange={e=>field("internal_notes",e.target.value)}/></div></div><div className="form-actions"><button className="button primary" disabled={saving} onClick={()=>save(["name","subtitle","category_id","season","material","origin","internal_notes"])}><Save size={15}/>保存基础信息</button></div></section>}
{tab===1&&<section className="panel"><div className="panel-head"><div><h2>SKU 与库存</h2><p>实际库存通过业务流水变化；网店上限可在这里直接更新并同步顾客网站</p></div></div>{product.product_variants?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>SKU</th><th>颜色</th><th>尺码</th><th>条形码</th><th>实际库存</th><th>占用</th><th>网店上限</th><th>状态</th></tr></thead><tbody>{product.product_variants.map((v:any)=>{const inv=v.inventory?.[0];return <tr key={v.id}><td><strong>{v.sku}</strong></td><td>{v.colors?.name}</td><td>{v.sizes?.name}</td><td>{v.barcode??"—"}</td><td>{inv?.quantity_on_hand??0}</td><td>{inv?.quantity_reserved??0}</td><td>{inv?<input className="table-input" style={{width:88,padding:"7px 9px"}} type="number" min="0" max={Math.max(0,(inv.quantity_on_hand??0)-(inv.quantity_reserved??0))} defaultValue={inv.online_quantity_limit??0} onBlur={e=>setOnlineLimit(inv.id,Number(e.target.value))}/>:"—"}</td><td><StatusBadge value={v.is_active?"VALID":"DRAFT"} label={v.is_active?"启用":"停用"}/></td></tr>})}</tbody></table></div>:<EmptyState title="还没有 SKU" description="可通过“新建并上架商品”窗口直接建立规格，或在确认入库时自动创建。"/>}</section>}
{tab===2&&<section className="form-card"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18}}><div><strong>商品图片</strong><div className="muted" style={{fontSize:11,marginTop:4}}>JPG / PNG / WebP，单张最大 10MB</div></div><label className="button primary"><ImagePlus size={15}/>上传图片<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/></label></div>{product.product_images?.length?<div className="product-grid">{product.product_images.map((img:any)=><div className="product-image" key={img.id}><img src={img.public_url} alt={product.name||product.style_no}/><button className="icon-btn" style={{position:"absolute",right:8,top:8}} onClick={()=>removeImage(img)}><Trash2 size={14}/></button>{img.is_primary&&<span className="product-pill">主图</span>}</div>)}</div>:<EmptyState title="还没有商品图片" description="至少上传一张主图和一张详情图后才能上架。"/>}</section>}
{tab===3&&<section className="form-card"><div className="form-grid"><div className="field"><label>成本价</label><input type="number" min="0" step="0.01" value={product.cost_price??""} onChange={e=>field("cost_price",e.target.value)}/></div><div className="field"><label>批发价</label><input type="number" min="0" step="0.01" value={product.wholesale_price??""} onChange={e=>field("wholesale_price",e.target.value)}/></div><div className="field"><label>建议零售价</label><input type="number" min="0" step="0.01" value={product.suggested_retail_price??""} onChange={e=>field("suggested_retail_price",e.target.value)}/></div><div className="field"><label>网店零售价 *</label><input type="number" min="0" step="0.01" value={product.retail_price??""} onChange={e=>field("retail_price",e.target.value)}/></div><div className="field"><label>促销价</label><input type="number" min="0" step="0.01" value={product.sale_price??""} onChange={e=>field("sale_price",e.target.value)}/></div><div className="field"><label>税率 %</label><input type="number" min="0" value={product.tax_rate??22} onChange={e=>field("tax_rate",e.target.value)}/></div></div><div className="form-actions"><button className="button primary" onClick={()=>save(["cost_price","wholesale_price","suggested_retail_price","retail_price","sale_price","tax_rate"])}><Save size={15}/>保存价格</button></div></section>}
{tab===4&&<section className="form-card"><div className="form-grid"><div className="field full"><label>商品详细描述 *</label><textarea value={product.description??""} onChange={e=>field("description",e.target.value)} placeholder="版型、设计、穿着场景与卖点"/></div><div className="field full"><label>洗涤说明</label><textarea value={product.care_instructions??""} onChange={e=>field("care_instructions",e.target.value)}/></div></div><div className="form-actions"><button className="button primary" onClick={()=>save(["description","care_instructions"])}><Save size={15}/>保存描述</button></div></section>}
{tab===5&&<section className="form-card"><div className="notice">已发布商品保存后会自动同步到顾客网站；首次发布前，系统仍会检查名称、主图、详情图、分类、价格、描述、唯一 URL 和可售库存。</div><div className="form-grid"><div className="field"><label>URL Slug</label><input value={product.slug??""} onChange={e=>field("slug",e.target.value.toLowerCase())} placeholder="例如 knit-cardigan-30283"/></div><div className="field"><label>SEO 标题</label><input value={product.seo_title??""} onChange={e=>field("seo_title",e.target.value)}/></div><div className="field full"><label>SEO 描述</label><textarea value={product.seo_description??""} onChange={e=>field("seo_description",e.target.value)}/></div></div><div className="flag-grid"><label><input type="checkbox" checked={product.is_new??true} onChange={e=>field("is_new",e.target.checked)}/><span><b>新品</b><small>显示新品标记</small></span></label><label><input type="checkbox" checked={product.is_featured??false} onChange={e=>field("is_featured",e.target.checked)}/><span><b>首页推荐</b><small>优先展示</small></span></label><label><input type="checkbox" checked={product.is_bestseller??false} onChange={e=>field("is_bestseller",e.target.checked)}/><span><b>畅销商品</b><small>显示畅销标记</small></span></label></div><div className="form-actions"><button className="button" onClick={()=>save(["slug","seo_title","seo_description","is_new","is_featured","is_bestseller"])}><Save size={15}/>保存并同步设置</button>{product.status==="PUBLISHED"?<button className="button danger" disabled={saving} onClick={unpublish}><EyeOff size={15}/>从顾客网站下架</button>:<button className="button primary" disabled={saving} onClick={publish}><Send size={15}/>发布到顾客网站</button>}</div></section>}
{tab===6&&<section className="panel"><EmptyState title="操作记录由系统自动生成" description="商品修改、价格变化、库存变化和上下架记录会进入不可篡改的审计日志。"/></section>}
</main>}
