import type { LocalizedText } from "./i18n";

export type LegalDocument = { title: LocalizedText; summary: LocalizedText; sections: Array<{ title: LocalizedText; body: LocalizedText }> };
const review = { it: "BOZZA EDITABILE — da verificare con un consulente legale italiano prima della messa online commerciale.", en: "EDITABLE DRAFT — must be reviewed by an Italian legal adviser before commercial launch.", zh: "可编辑占位模板——正式上线前需意大利法律顾问确认。" };
const placeholder = (it: string, en: string, zh: string) => ({ it: `[DA COMPLETARE] ${it}`, en: `[TO COMPLETE] ${en}`, zh: `[待补充] ${zh}` });

export const legalDocuments: Record<string, LegalDocument> = {
  "condizioni-generali-di-vendita": { title: { it: "Condizioni generali di vendita", en: "General terms of sale", zh: "销售通用条款" }, summary: review, sections: [
    { title: { it: "Venditore e ambito", en: "Seller and scope", zh: "销售方与适用范围" }, body: { it: "Venditore: VICTOR S.R.L., P. IVA / C.F. 08788801218. Questo testo non costituisce ancora una versione legale definitiva.", en: "Seller: VICTOR S.R.L., VAT / tax code 08788801218. This is not yet a final legal version.", zh: "销售方：VICTOR S.R.L.，P. IVA / C.F. 08788801218。本页尚非最终法律版本。" } },
    { title: { it: "Ordine, prezzo e pagamento", en: "Order, price and payment", zh: "订单、价格与付款" }, body: placeholder("definire conclusione del contratto, correzione errori di prezzo, IVA, pagamento e conferma ordine.", "define contract formation, price error correction, VAT, payment and order confirmation.", "明确合同成立、价格错误更正、IVA、付款和订单确认规则。") },
    { title: { it: "Consegna, recesso e responsabilità", en: "Delivery, withdrawal and liability", zh: "交付、撤回与责任" }, body: placeholder("coordinare con le pagine dedicate e inserire limiti conformi alla normativa applicabile.", "align with the dedicated pages and add limits compliant with applicable law.", "与专项页面保持一致，并加入符合适用法律的责任限制。") },
  ] },
  privacy: { title: { it: "Privacy Policy", en: "Privacy Policy", zh: "隐私政策" }, summary: review, sections: [
    { title: { it: "Titolare del trattamento", en: "Data controller", zh: "数据控制者" }, body: { it: "Titolare indicato: VICTOR S.R.L. Dati di contatto privacy e indirizzo completo devono essere confermati.", en: "Named controller: VICTOR S.R.L. Privacy contact details and full address must be confirmed.", zh: "暂列数据控制者：VICTOR S.R.L.；隐私联系信息和完整地址需确认。" } },
    { title: { it: "Dati, finalità e basi giuridiche", en: "Data, purposes and legal bases", zh: "数据、目的与法律依据" }, body: placeholder("mappare dati account, ordine, consegna, assistenza, log tecnici e relative basi giuridiche.", "map account, order, delivery, support and technical-log data with their legal bases.", "梳理账户、订单、配送、客服、技术日志数据及相应法律依据。") },
    { title: { it: "Conservazione e diritti", en: "Retention and rights", zh: "保存期限与权利" }, body: placeholder("inserire tempi di conservazione, destinatari, trasferimenti, diritti e canali di esercizio.", "add retention periods, recipients, transfers, rights and request channels.", "补充保存期限、接收方、跨境传输、权利及行使渠道。") },
  ] },
  cookie: { title: { it: "Cookie Policy", en: "Cookie Policy", zh: "Cookie 政策" }, summary: review, sections: [
    { title: { it: "Tecnologie necessarie", en: "Necessary technologies", zh: "必要技术" }, body: { it: "Il sito usa archiviazione locale per borsa, lingua e sessione ospite. Verificare l'inventario tecnico prima del lancio.", en: "The site uses local storage for bag, language and guest session. Verify the technical inventory before launch.", zh: "网站使用本地存储保存购物袋、语言和访客会话；上线前需核对技术清单。" } },
    { title: { it: "Cookie non necessari", en: "Non-essential cookies", zh: "非必要 Cookie" }, body: placeholder("elencare analytics, marketing e terze parti soltanto se effettivamente installati, con durata e fornitore.", "list analytics, marketing and third parties only if actually installed, including duration and provider.", "仅在实际安装时列出分析、营销和第三方 Cookie，并注明期限与提供方。") },
    { title: { it: "Consenso", en: "Consent", zh: "同意管理" }, body: placeholder("definire banner, preferenze, revoca e prova del consenso se saranno usati cookie non necessari.", "define banner, preferences, withdrawal and consent records if non-essential cookies are used.", "如使用非必要 Cookie，需明确横幅、偏好、撤回和同意记录机制。") },
  ] },
  "spedizioni-e-consegne": { title: { it: "Spedizioni e consegne", en: "Shipping and delivery", zh: "配送与交付" }, summary: review, sections: [
    { title: { it: "Copertura e costi", en: "Coverage and costs", zh: "范围与费用" }, body: { it: "Configurazione tecnica attuale: consegna in Italia, costo stimato €6,90 e gratuita da €99; il server ricalcola il costo finale.", en: "Current technical configuration: delivery in Italy, estimated €6.90 and free from €99; the server recalculates the final cost.", zh: "当前技术配置：意大利境内配送，预计 €6.90，满 €99 免运费；最终费用由服务器重算。" } },
    { title: { it: "Tempi e vettore", en: "Timing and carrier", zh: "时效与承运商" }, body: placeholder("indicare vettori, zone, tempi di preparazione e consegna solo dopo accordi operativi reali.", "state carriers, zones, preparation and delivery times only after real operational agreements.", "仅在真实运营协议确定后填写承运商、区域、备货与配送时效。") },
    { title: { it: "Ritiro in negozio", en: "Store pickup", zh: "门店自取" }, body: placeholder("confermare indirizzo, orari, termine di giacenza, delega e documento richiesto al ritiro.", "confirm address, opening hours, holding period, proxy pickup and required identification.", "确认地址、营业时间、保留期限、代取及所需证件。") },
  ] },
  "resi-e-recesso": { title: { it: "Resi e diritto di recesso", en: "Returns and withdrawal", zh: "退货与撤回权" }, summary: review, sections: [
    { title: { it: "Diritto di recesso", en: "Right of withdrawal", zh: "撤回权" }, body: placeholder("inserire termini, decorrenza, eccezioni e modulo dopo verifica legale italiana.", "add period, start date, exceptions and form after Italian legal review.", "经意大利法律顾问确认后填写期限、起算、例外和表格。") },
    { title: { it: "Procedura di reso", en: "Return process", zh: "退货流程" }, body: placeholder("definire richiesta, autorizzazione, indirizzo, costi, condizioni del bene e prova di spedizione.", "define request, authorisation, address, costs, item condition and shipping evidence.", "明确申请、授权、地址、费用、商品状态和寄送凭证。") },
    { title: { it: "Rimborso", en: "Refund", zh: "退款" }, body: { it: "Non viene indicato alcun rimborso automatico: senza un gateway reale, ogni rimborso deve essere verificato e registrato dal personale.", en: "No automatic refund is claimed: without a real gateway, each refund must be verified and recorded by staff.", zh: "本系统不宣称自动退款成功；未接入真实支付网关时，每笔退款须由员工核验并记录。" } },
  ] },
  "metodi-di-pagamento": { title: { it: "Metodi di pagamento", en: "Payment methods", zh: "付款方式" }, summary: review, sections: [
    { title: { it: "Pagamento online", en: "Online payment", zh: "在线付款" }, body: { it: "Il gateway reale non è collegato. Un ordine di consegna può essere registrato come in attesa, ma il sito non mostra un pagamento riuscito e non effettua addebiti.", en: "A real gateway is not connected. A delivery order may be recorded as pending, but the site does not show a successful payment or charge the customer.", zh: "尚未连接真实支付网关。配送订单可记录为待付款，但网站不会显示付款成功，也不会扣款。" } },
    { title: { it: "Pagamento al ritiro", en: "Payment on pickup", zh: "自取到店付款" }, body: { it: "Disponibile soltanto per gli ordini con ritiro in negozio e da confermare operativamente prima del lancio.", en: "Available only for store-pickup orders and subject to operational confirmation before launch.", zh: "仅适用于门店自取订单，正式上线前仍需运营确认。" } },
    { title: { it: "Metodi futuri", en: "Future methods", zh: "未来方式" }, body: placeholder("elencare carte, wallet o altri strumenti solo dopo contratto, integrazione e test reali.", "list cards, wallets or other methods only after real contracting, integration and testing.", "仅在完成真实签约、接入和测试后列出银行卡、钱包或其他方式。") },
  ] },
  "garanzia-legale": { title: { it: "Garanzia legale", en: "Legal guarantee", zh: "法定担保" }, summary: review, sections: [
    { title: { it: "Ambito", en: "Scope", zh: "适用范围" }, body: placeholder("descrivere la garanzia legale di conformità con termini ed esclusioni verificati da un consulente.", "describe the legal conformity guarantee with periods and exclusions reviewed by counsel.", "由法律顾问确认后说明法定合规担保的期限与例外。") },
    { title: { it: "Segnalazione", en: "Making a claim", zh: "提出主张" }, body: placeholder("indicare canale, informazioni richieste, prova d'acquisto e gestione del bene.", "state the contact channel, required information, proof of purchase and item handling.", "明确联系渠道、所需资料、购买凭证和商品处理方式。") },
    { title: { it: "Rimedi", en: "Remedies", zh: "救济方式" }, body: placeholder("inserire rimedi e priorità senza anticipare conclusioni legali non verificate.", "add remedies and priorities without making unverified legal conclusions.", "补充救济方式及顺序，不作未经确认的法律结论。") },
  ] },
  contatti: { title: { it: "Contatti", en: "Contact", zh: "联系我们" }, summary: review, sections: [
    { title: { it: "Servizio clienti", en: "Customer service", zh: "顾客服务" }, body: { it: "Email operativa indicata: xrx020526@gmail.com. Confermare SLA, orari e indirizzo del punto vendita prima del lancio.", en: "Current operating email: xrx020526@gmail.com. Confirm service times, hours and store address before launch.", zh: "当前运营邮箱：xrx020526@gmail.com。上线前需确认响应时效、工作时间和门店地址。" } },
    { title: { it: "Società", en: "Company", zh: "公司" }, body: { it: "VICTOR S.R.L. · P. IVA / C.F. 08788801218 · REA NA-984973.", en: "VICTOR S.R.L. · VAT / tax code 08788801218 · REA NA-984973.", zh: "VICTOR S.R.L. · P. IVA / C.F. 08788801218 · REA NA-984973。" } },
    { title: { it: "Reclami e privacy", en: "Complaints and privacy", zh: "投诉与隐私" }, body: placeholder("confermare indirizzi dedicati e procedura di escalation.", "confirm dedicated addresses and escalation procedure.", "确认专用联系地址和升级处理流程。") },
  ] },
};
