"use client";

import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Leaf, RotateCcw, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { storefrontErrorMessage } from "@/lib/i18n";
import { loadStorefrontCatalog } from "@/lib/storefront-data";
import type { StorefrontProduct } from "@/lib/store-types";
import { useLocale } from "./locale-provider";
import { ProductCard } from "./product-card";

const copy = {
  it: { heroAlt: "Tre donne indossano la collezione urbana NEXORA STUDIO", hero: "NEXORA STUDIO, per ogni momento", explore: "Scopri le novità", title: "I vestiti non devono definirti.\nDevono stare al tuo passo.", intro: "Dall'ufficio alla passeggiata serale, dal fine settimana in città a un viaggio improvviso: materiali confortevoli, linee pulite e colori facili da abbinare.", collections: [{ label: "CITY", title: "Ufficio", body: "Linee precise, comfort naturale", value: "work" }, { label: "MOVE", title: "Active leggero", body: "Dallo stretching al fine settimana", value: "light-active" }, { label: "ESCAPE", title: "Viaggio", body: "Partire leggeri, vestirsi a strati", value: "travel" }], shopCollection: "Scopri la collezione", justIn: "Appena arrivati", viewAll: "Vedi tutto", loading: "Collegamento a prodotti e disponibilità…", error: "Il catalogo non è disponibile", retry: "Riprova", coming: "La prima selezione è in preparazione", comingBody: "Gli articoli appariranno qui solo dopo il controllo di immagini, prezzo e disponibilità.", colorTitle: "Rosso bacca,\nenergia quotidiana.", colorBody: "Un accento equilibrato da abbinare a nero, avena o verde salvia.", colorLink: "Scopri la palette", stock: "Disponibilità reale", stockBody: "Ricontrollata dal server al checkout", returns: "Resi trasparenti", returnsBody: "Consulta condizioni e procedura prima dell'acquisto", fewer: "Meno capi, più combinazioni", fewerBody: "Selezionati per essere indossati spesso" },
  en: { heroAlt: "Three women wear the NEXORA STUDIO city collection", hero: "NEXORA STUDIO, for every moment", explore: "Explore new arrivals", title: "Clothes do not need to define you.\nThey should keep up with you.", intro: "From work to evening walks, city weekends to unplanned trips: comfortable materials, clear lines and colours made to work together.", collections: [{ label: "CITY", title: "Work", body: "Clean lines, effortless comfort", value: "work" }, { label: "MOVE", title: "Light active", body: "From stretching to weekend walks", value: "light-active" }, { label: "ESCAPE", title: "Travel", body: "Pack light and layer well", value: "travel" }], shopCollection: "Shop collection", justIn: "Just in", viewAll: "View all", loading: "Connecting products and availability…", error: "The catalogue is unavailable", retry: "Retry", coming: "The first selection is being prepared", comingBody: "Items appear only after imagery, price and availability checks.", colorTitle: "Berry red,\neveryday energy.", colorBody: "A balanced accent with black, oat or soft sage.", colorLink: "Explore the palette", stock: "Real availability", stockBody: "Checked again by the server at checkout", returns: "Clear returns", returnsBody: "Read the conditions and process before purchase", fewer: "Fewer pieces, more outfits", fewerBody: "Selected to be worn often" },
  zh: { heroAlt: "三位女性穿着 NEXORA STUDIO 城市生活系列", hero: "NEXORA STUDIO，为每一种状态而穿", explore: "探索新品", title: "衣服不需要定义你。\n它应该跟得上你。", intro: "从早晨通勤到晚间散步，从城市周末到临时旅行。我们选择舒适面料、清晰线条和可以反复搭配的颜色。", collections: [{ label: "CITY", title: "通勤", body: "线条利落，保持松弛", value: "work" }, { label: "MOVE", title: "轻运动", body: "从伸展到周末漫步", value: "light-active" }, { label: "ESCAPE", title: "旅行", body: "轻装出发，叠穿有序", value: "travel" }], shopCollection: "选购系列", justIn: "刚刚上新", viewAll: "查看全部", loading: "正在连接最新商品与库存…", error: "商品暂时无法读取", retry: "重试", coming: "第一批精选正在准备", comingBody: "商品完成图片、价格和库存检查后才会出现在这里。", colorTitle: "莓红，\n给日常一点力量。", colorBody: "一抹不过度张扬的色彩，配黑色、燕麦色或柔和鼠尾草绿。", colorLink: "探索颜色故事", stock: "真实可售库存", stockBody: "结账时由服务端再次校验", returns: "清晰退换流程", returnsBody: "购买前可查阅条件与流程", fewer: "买得更少，更常穿", fewerBody: "以搭配率为选品标准" },
} as const;

export function HomeStorefront() {
  const { locale, href } = useLocale();
  const words = copy[locale];
  const [products, setProducts] = useState<StorefrontProduct[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { void loadStorefrontCatalog({ limit: 8 }).then((result) => { setProducts(result.products); setError(result.error); setLoading(false); }); }, []);
  return <main>
    <section className="campaign-hero"><Image src="/hero-campaign.webp" alt={words.heroAlt} fill priority sizes="100vw" /><h1 className="sr-only">{words.hero}</h1><Link className="hero-cta" href={href("/shop?filter=new")}>{words.explore} <ArrowRight /></Link></section>
    <section className="intro-section"><p className="section-kicker">THE EVERYDAY EDIT</p><h2>{words.title.split("\n").map((line) => <span key={line}>{line}<br/></span>)}</h2><p>{words.intro}</p></section>
    <section className="edit-grid" aria-label="Collections">{words.collections.map((edit, index) => <Link className={`edit-card ${["berry", "sage", "sand"][index]}`} href={href(`/shop?collection=${edit.value}`)} key={edit.label}><span>0{index + 1} / {edit.label}</span><div><h3>{edit.title}</h3><p>{edit.body}</p><b>{words.shopCollection} <ArrowRight /></b></div></Link>)}</section>
    <section className="products-section"><div className="section-heading"><div><p className="section-kicker">NEW & NOTEWORTHY</p><h2>{words.justIn}</h2></div><Link href={href("/shop")}>{words.viewAll} <ArrowRight /></Link></div>{loading ? <div className="product-loading" aria-live="polite">{words.loading}</div> : error ? <div className="launch-state"><Sparkles /><div><h3>{words.error}</h3><p>{storefrontErrorMessage(error, locale)}</p></div><button className="text-link" onClick={() => window.location.reload()}>{words.retry}</button></div> : products.length ? <div className="product-grid">{products.map((product) => <ProductCard product={product} key={product.id} />)}</div> : <div className="launch-state"><Sparkles /><div><p className="section-kicker">COMING SOON</p><h3>{words.coming}</h3><p>{words.comingBody}</p></div><Link className="text-link" href={href("/shop")}>{words.viewAll} <ArrowRight /></Link></div>}</section>
    <section className="colour-story"><div><p className="section-kicker">COLOUR STORY · 01</p><h2>{words.colorTitle.split("\n").map((line) => <span key={line}>{line}<br/></span>)}</h2><p>{words.colorBody}</p><Link href={href("/shop?color=berry")}>{words.colorLink} <ArrowRight /></Link></div><div className="colour-panels"><span/><span/><span/></div></section>
    <section className="service-strip"><div><ShieldCheck /><strong>{words.stock}</strong><span>{words.stockBody}</span></div><div><RotateCcw /><strong>{words.returns}</strong><span>{words.returnsBody}</span></div><div><Leaf /><strong>{words.fewer}</strong><span>{words.fewerBody}</span></div></section>
  </main>;
}
