"use client";

import Link from "next/link";
import { CheckCircle2, Clock3, PackageCheck } from "lucide-react";
import { CustomerOrderActions } from "@/components/customer-order-actions";
import { useLocale } from "@/components/locale-provider";
import { localeTags } from "@/lib/i18n";
import { formatPrice, type StorefrontOrder } from "@/lib/store-types";

const labels = {
  it: { lifecycle: { draft: "Bozza", pending: "Ordine ricevuto", confirmed: "Ordine confermato", processing: "In lavorazione", completed: "Completato", cancelled: "Annullato" }, payment: { unpaid: "Non pagato", pending: "Pagamento in attesa", paid: "Pagato", partially_refunded: "Rimborso parziale", refunded: "Rimborsato", failed: "Pagamento non riuscito" }, fulfillment: { unfulfilled: "Da preparare", reserved: "Disponibilità riservata", picking: "Prelievo", packed: "Imballato", shipped: "Spedito", ready_pickup: "Pronto al ritiro", delivered: "Consegnato", picked_up: "Ritirato" }, intro: "Ordine, pagamento e consegna sono registrati separatamente. Questo messaggio non indica un pagamento riuscito.", order: "Ordine", pay: "Pagamento", fulfill: "Consegna", amount: "Importo", method: "Metodo", pickup: "Ritiro in negozio", delivery: "Spedizione", date: "Data ordine", timeline: "Aggiornamenti", continue: "Continua lo shopping", account: "Ordini dell'account" },
  en: { lifecycle: { draft: "Draft", pending: "Order received", confirmed: "Order confirmed", processing: "Processing", completed: "Completed", cancelled: "Cancelled" }, payment: { unpaid: "Unpaid", pending: "Payment pending", paid: "Paid", partially_refunded: "Partially refunded", refunded: "Refunded", failed: "Payment failed" }, fulfillment: { unfulfilled: "Unfulfilled", reserved: "Availability reserved", picking: "Picking", packed: "Packed", shipped: "Shipped", ready_pickup: "Ready for pickup", delivered: "Delivered", picked_up: "Picked up" }, intro: "Order, payment and fulfilment are recorded separately. This message does not indicate a successful payment.", order: "Order", pay: "Payment", fulfill: "Fulfilment", amount: "Amount", method: "Method", pickup: "Store pickup", delivery: "Delivery", date: "Order date", timeline: "Updates", continue: "Continue shopping", account: "Account orders" },
  zh: { lifecycle: { draft: "草稿", pending: "订单已收到", confirmed: "订单已确认", processing: "订单处理中", completed: "订单已完成", cancelled: "订单已取消" }, payment: { unpaid: "未付款", pending: "等待付款", paid: "已付款", partially_refunded: "部分退款", refunded: "已退款", failed: "付款失败" }, fulfillment: { unfulfilled: "未履约", reserved: "库存已预留", picking: "正在拣货", packed: "已打包", shipped: "已发货", ready_pickup: "可以到店领取", delivered: "已送达", picked_up: "已领取" }, intro: "订单、付款与履约进度分别记录；本提示不表示付款成功。", order: "订单", pay: "付款", fulfill: "履约", amount: "订单金额", method: "配送方式", pickup: "门店自取", delivery: "快递配送", date: "下单时间", timeline: "订单进度", continue: "继续选购", account: "查看账户订单" },
} as const;

export function OrderSummaryCard({ order }: { order: StorefrontOrder }) {
  const { locale, href } = useLocale(); const copy = labels[locale];
  const lifecycle = order.lifecycle_status || (order.status === "CANCELLED" ? "cancelled" : "pending"); const payment = order.payment_status.toLowerCase(); const fulfillment = order.fulfillment_status || "reserved";
  const lifecycleLabel = copy.lifecycle[lifecycle as keyof typeof copy.lifecycle] ?? lifecycle; const paymentLabel = copy.payment[payment as keyof typeof copy.payment] ?? payment; const fulfillmentLabel = copy.fulfillment[fulfillment as keyof typeof copy.fulfillment] ?? fulfillment;
  return <article className="order-confirmation-card"><div className="order-success-icon">{lifecycle === "pending" ? <Clock3 /> : lifecycle === "completed" ? <CheckCircle2 /> : <PackageCheck />}</div><p className="section-kicker">ORDER {order.order_no}</p><h1>{lifecycleLabel}</h1><p>{copy.intro}</p><div className="customer-order-states"><span><small>{copy.order}</small><strong>{lifecycleLabel}</strong></span><span><small>{copy.pay}</small><strong>{paymentLabel}</strong></span><span><small>{copy.fulfill}</small><strong>{fulfillmentLabel}</strong></span></div><dl><div><dt>{copy.amount}</dt><dd>{formatPrice(order.total_amount, order.currency)}</dd></div><div><dt>{copy.method}</dt><dd>{order.fulfillment_method === "PICKUP" ? copy.pickup : copy.delivery}</dd></div><div><dt>{copy.pay}</dt><dd>{paymentLabel}</dd></div><div><dt>{copy.date}</dt><dd>{new Date(order.created_at).toLocaleString(localeTags[locale])}</dd></div></dl><div className="confirmation-items">{order.items.map((item) => <div key={item.id}><span>{item.product_title}<small>{item.color_name} / {item.size_name} · {item.sku} × {item.quantity}</small></span><strong>{formatPrice(item.line_total, item.currency)}</strong></div>)}</div>{order.events?.length > 0 && <div className="customer-order-timeline"><h2>{copy.timeline}</h2>{order.events.map((event) => <div key={event.id}><i /><span><strong>{event.message || event.event_type}</strong><small>{new Date(event.occurred_at).toLocaleString(localeTags[locale])}</small></span></div>)}</div>}<CustomerOrderActions order={order} /><div className="confirmation-actions"><Link className="primary-link" href={href("/shop")}>{copy.continue}</Link><Link href={href("/account/orders")}>{copy.account}</Link></div></article>;
}
