"use client";

import Link from "next/link";
import { Menu, Search, ShoppingBag, UserRound, X } from "lucide-react";
import { useEffect, useState } from "react";
import { collectionCategories, garmentCategories } from "@/lib/catalog";
import { ui, type StoreLocale } from "@/lib/i18n";
import { loadStorefrontCatalog } from "@/lib/storefront-data";
import { useCart } from "./cart-provider";
import { useLocale } from "./locale-provider";

const languageLabels: Record<StoreLocale, string> = { it: "IT", en: "EN", zh: "中文" };

export function StoreShell({ children }: { children: React.ReactNode }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [hasSale, setHasSale] = useState(false);
  const { count } = useCart();
  const { locale, href, switchLocale } = useLocale();
  const copy = ui[locale];
  useEffect(() => {
    void loadStorefrontCatalog({ limit: 200 }).then(({ products }) => setHasSale(products.some((product) => Boolean(product.compare_at_price && product.compare_at_price > product.unit_price))));
  }, []);
  const closeMenu = () => setMenuOpen(false);
  return <><div className="announcement">{copy.announcement}</div><header className="site-header"><button className="mobile-menu-button" onClick={() => setMenuOpen(true)} aria-label={copy.openMenu}><Menu /></button><Link className="wordmark" href={href("/")}>NEXORA <span>STUDIO</span></Link><nav className="desktop-nav" aria-label="Catalogo donna"><Link href={href("/shop?filter=new")}>{copy.new}</Link><details className="nav-mega"><summary>{copy.women}</summary><div className="nav-mega-panel"><div><strong>{copy.all}</strong><Link href={href("/shop")}>{copy.all}</Link>{garmentCategories.map((category) => <Link key={category.slug} href={href(`/shop?category=${category.slug}`)}>{category.label[locale]}</Link>)}</div><div><strong>{locale === "it" ? "Collezioni" : locale === "en" ? "Collections" : "系列"}</strong>{collectionCategories.map((category) => <Link key={category.slug} href={href(`/shop?collection=${category.slug}`)}>{category.label[locale]}</Link>)}</div></div></details><Link href={href("/shop?filter=bestseller")}>{copy.bestsellers}</Link>{hasSale && <Link href={href("/shop?filter=sale")}>{copy.sale}</Link>}<Link href={href("/company")}>{copy.company}</Link></nav><div className="header-actions"><label className="language-select"><span className="sr-only">{copy.chooseLanguage}</span><select aria-label={copy.chooseLanguage} value={locale} onChange={(event) => switchLocale(event.target.value as StoreLocale)}>{(Object.keys(languageLabels) as StoreLocale[]).map((key) => <option key={key} value={key}>{languageLabels[key]}</option>)}</select></label><Link href={href("/shop")} aria-label={copy.search}><Search /></Link><Link href={href("/account/orders")} aria-label={copy.account}><UserRound /></Link><Link className="bag-link" href={href("/bag")} aria-label={`${copy.bag}, ${count}`}><ShoppingBag />{count > 0 && <span>{count}</span>}</Link></div></header>
    {menuOpen && <div className="mobile-menu" role="dialog" aria-modal="true"><button onClick={closeMenu} aria-label={copy.close}><X /></button><Link className="wordmark" href={href("/")} onClick={closeMenu}>NEXORA <span>STUDIO</span></Link><nav><Link href={href("/shop?filter=new")} onClick={closeMenu}>{copy.new}</Link><Link href={href("/shop")} onClick={closeMenu}>{copy.all}</Link>{garmentCategories.map((category) => <Link href={href(`/shop?category=${category.slug}`)} onClick={closeMenu} key={category.slug}>{category.label[locale]}</Link>)}<strong>{locale === "it" ? "Collezioni" : locale === "en" ? "Collections" : "系列"}</strong>{collectionCategories.map((category) => <Link href={href(`/shop?collection=${category.slug}`)} onClick={closeMenu} key={category.slug}>{category.label[locale]}</Link>)}<Link href={href("/shop?filter=bestseller")} onClick={closeMenu}>{copy.bestsellers}</Link>{hasSale && <Link href={href("/shop?filter=sale")} onClick={closeMenu}>{copy.sale}</Link>}<Link href={href("/account/orders")} onClick={closeMenu}>{copy.account}</Link><Link href={href("/order-lookup")} onClick={closeMenu}>{locale === "it" ? "Cerca ordine ospite" : locale === "en" ? "Guest order lookup" : "访客订单查询"}</Link><Link href={href("/company")} onClick={closeMenu}>{copy.company}</Link></nav></div>}
    {children}<footer className="site-footer"><div><Link className="wordmark light" href={href("/")}>NEXORA <span>STUDIO</span></Link><p>{locale === "it" ? "Abbigliamento donna essenziale per l'ufficio, il quotidiano, il viaggio, il movimento leggero e la sera." : locale === "en" ? "Essential womenswear for work, everyday life, travel, light movement and evenings." : "为女性的通勤、日常、旅行、轻运动与晚间场景提供舒适、利落、易搭配的女装。"}</p></div><div><strong>{locale === "it" ? "Acquista" : locale === "en" ? "Shop" : "选购"}</strong><Link href={href("/shop")}>{copy.all}</Link><Link href={href("/shop?filter=new")}>{copy.new}</Link><Link href={href("/shop?filter=bestseller")}>{copy.bestsellers}</Link>{hasSale && <Link href={href("/shop?filter=sale")}>{copy.sale}</Link>}<Link href={href("/bag")}>{copy.bag}</Link></div><div><strong>{locale === "it" ? "Servizio clienti" : locale === "en" ? "Customer care" : "顾客服务"}</strong><Link href={href("/login")}>{locale === "it" ? "Accedi / Registrati" : locale === "en" ? "Sign in / Register" : "登录 / 注册"}</Link><Link href={href("/account/orders")}>{locale === "it" ? "I miei ordini" : locale === "en" ? "My orders" : "我的订单"}</Link><Link href={href("/spedizioni-e-consegne")}>{locale === "it" ? "Spedizioni e consegne" : locale === "en" ? "Shipping & delivery" : "配送与交付"}</Link><Link href={href("/resi-e-recesso")}>{locale === "it" ? "Resi e diritto di recesso" : locale === "en" ? "Returns & withdrawal" : "退货与撤回权"}</Link><Link href={href("/contatti")}>{locale === "it" ? "Contatti" : locale === "en" ? "Contact" : "联系我们"}</Link></div><div><strong>{locale === "it" ? "Informazioni legali" : locale === "en" ? "Legal" : "法律信息"}</strong><Link href={href("/condizioni-generali-di-vendita")}>Condizioni generali di vendita</Link><Link href={href("/privacy")}>Privacy Policy</Link><Link href={href("/cookie")}>Cookie Policy</Link><Link href={href("/metodi-di-pagamento")}>Metodi di pagamento</Link><Link href={href("/garanzia-legale")}>Garanzia legale</Link><Link href={href("/company")}>{copy.company}</Link></div><small>© 2026 VICTOR S.R.L. · P. IVA / C.F. 08788801218 · {locale === "it" ? "Il sito non memorizza dati completi delle carte" : locale === "en" ? "The site does not store full card data" : "网站不存储完整银行卡资料"}</small></footer></>;
}
