"use client";
import { useCallback } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { PageHead } from "@/components/shared/page-head";
import { SetupBanner } from "@/components/shared/setup-banner";
import { EmptyState } from "@/components/shared/empty-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { useSupabaseQuery } from "@/hooks/use-supabase-query";
const EMPTY:any[]=[];
export default function ParseReview(){const {id}=useParams<{id:string}>();const query=useCallback((c:any)=>c.from("stock_receipt_items").select("id,raw_line_number,raw_style_no,normalized_style_no,normalized_color,normalized_size,expected_quantity,received_quantity,status,notes").eq("receipt_id",id).order("raw_line_number"),[id]);const {data}=useSupabaseQuery<any[]>(query,EMPTY);const total=data.reduce((a,r)=>a+(r.expected_quantity??0),0);return <main className="page"><PageHead eyebrow="PARSE REVIEW" title="检查解析结果" subtitle="逐项确认款号、颜色、尺码与货单数量，不明确的内容必须人工处理。" action={<Link className="button" href="/warehouse/receipts"><ArrowLeft size={15}/>入库记录</Link>}/><SetupBanner/><div className="progress-line"><span className="progress-step done"><i>✓</i>导入货单</span><span className="progress-rule"/><span className="progress-step active"><i>2</i>解析检查</span><span className="progress-rule"/><span className="progress-step"><i>3</i>实收核对</span><span className="progress-rule"/><span className="progress-step"><i>4</i>确认入库</span></div><section className="panel"><div className="panel-head"><div><h2>解析明细</h2><p>{data.length} 个 SKU，共 {total} 件</p></div><Link className="button primary panel-action" href={`/warehouse/receipts/${id}/receive`}>进入实收核对 <ArrowRight size={15}/></Link></div>{data.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>原始行</th><th>原始款号</th><th>标准款号</th><th>颜色</th><th>尺码</th><th>数量</th><th>状态</th><th>提示</th></tr></thead><tbody>{data.map(r=><tr key={r.id}><td>{r.raw_line_number}</td><td className="muted">{r.raw_style_no}</td><td><strong>{r.normalized_style_no}</strong></td><td>{r.normalized_color}</td><td>{r.normalized_size}</td><td>{r.expected_quantity}</td><td><StatusBadge value={r.status}/></td><td className="muted">{r.notes??"—"}</td></tr>)}</tbody></table></div>:<EmptyState title="没有解析明细" description="这张入库单尚未保存任何有效货单行。"/>}</section></main>}
