"use client";
import { useCallback, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, CheckCircle2, LoaderCircle, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { PageHead } from "@/components/shared/page-head";
import { SetupBanner } from "@/components/shared/setup-banner";
import { StatCard } from "@/components/shared/stat-card";
import { useSupabaseQuery } from "@/hooks/use-supabase-query";
import { friendlyError } from "@/lib/errors/friendly-error";
import { getSupabase } from "@/lib/supabase/client";
const EMPTY:any[]=[];
export default function Confirm(){const {id}=useParams<{id:string}>();const router=useRouter();const query=useCallback((c:any)=>c.from("stock_receipt_items").select("id,normalized_style_no,normalized_color,normalized_size,received_quantity,difference_quantity,match_type,status").eq("receipt_id",id),[id]);const {data}=useSupabaseQuery<any[]>(query,EMPTY);const [loading,setLoading]=useState(false);const [message,setMessage]=useState("");const styles=new Set(data.map(x=>x.normalized_style_no)).size,total=data.reduce((a,x)=>a+(x.received_quantity??0),0),diffs=data.filter(x=>x.difference_quantity!==0).length;async function confirm(){const client=getSupabase();if(!client){setMessage("请先连接 Supabase。");return;}setLoading(true);const {data,error}=await client.rpc("confirm_stock_receipt",{p_receipt_id:id});const result=data as {total_quantity?:number}|null;if(error){setMessage(friendlyError(error,"入库失败，库存未发生变化。"));setLoading(false);return;}setMessage(`入库成功，共更新 ${result?.total_quantity??total} 件库存。`);setLoading(false);setTimeout(()=>router.push("/warehouse/receipts"),900);}
return <main className="page"><PageHead eyebrow="CONFIRM RECEIPT" title="确认全部入库" subtitle="本操作在一个数据库事务中创建商品、SKU、库存与流水，失败将整体回滚。" action={<Link className="button" href={`/warehouse/receipts/${id}/receive`}><ArrowLeft size={15}/>返回实收核对</Link>}/><SetupBanner/><div className="progress-line"><span className="progress-step done"><i>✓</i>导入货单</span><span className="progress-rule"/><span className="progress-step done"><i>✓</i>解析检查</span><span className="progress-rule"/><span className="progress-step done"><i>✓</i>实收核对</span><span className="progress-rule"/><span className="progress-step active"><i>4</i>确认入库</span></div><section className="stats-grid"><StatCard label="总款号" value={styles} icon={ShieldCheck}/><StatCard label="总 SKU" value={data.length} icon={CheckCircle2}/><StatCard label="实收总件数" value={total} icon={CheckCircle2}/><StatCard label="差异 SKU" value={diffs} icon={ShieldCheck}/></section><section className="form-card"><div className="notice"><strong>库存安全检查</strong><br/>系统会锁定入库单并拒绝重复确认；每一个库存变化都会生成含入库单号、操作人、变更前后数量的库存流水。</div>{message&&<div className={message.includes("成功")?"notice":"notice warning"}>{message}</div>}<div className="form-actions"><button className="button primary" disabled={loading||!data.length} onClick={confirm}>{loading?<LoaderCircle size={16}/>:<ShieldCheck size={16}/>} {loading?"正在执行事务…":"确认全部入库"}</button></div></section></main>}
