"use client";
import { useCallback, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { Minus, Plus, ShoppingBag } from "lucide-react";
import { useSupabaseQuery } from "@/hooks/use-supabase-query";
import { EmptyState } from "@/components/shared/empty-state";
import { getSupabase } from "@/lib/supabase/client";
const EMPTY:any[]=[];
export default function ProductDetail(){const {slug}=useParams<{slug:string}>();const query=useCallback((c:any)=>c.from("online_listings").select("*,products(*,product_images(*),product_variants(*,colors(name),sizes(name),inventory(*)))").eq("slug",slug).eq("listing_status","PUBLISHED").limit(1),[slug]);const {data}=useSupabaseQuery<any[]>(query,EMPTY);const listing=data[0];const [variantId,setVariantId]=useState("");const [qty,setQty]=useState(1);const [message,setMessage]=useState("");const product=listing?.products;const variants=product?.product_variants??[];const selected=variants.find((x:any)=>x.id===(variantId||variants[0]?.id));const available=useMemo(()=>{const inv=selected?.inventory?.[0];return inv?Math.min(Math.max(0,inv.quantity_on_hand-inv.quantity_reserved),inv.online_quantity_limit):0;},[selected]);async function add(){const c=getSupabase();if(!c){setMessage("商店尚未连接数据库。");return;}const {data:user}=await c.auth.getUser();if(!user.user){setMessage("请先登录后加入购物车。");return;}if(qty>available){setMessage(`库存不足，当前最多可购买 ${available} 件。`);return;}const {data:cart,error}=await c.from("shopping_carts").upsert({customer_id:user.user.id,status:"ACTIVE"},{onConflict:"customer_id,status"}).select("id").single();if(error||!cart){setMessage(error?.message??"创建购物车失败");return;}const {error:itemError}=await c.from("shopping_cart_items").upsert({cart_id:cart.id,variant_id:selected.id,quantity:qty,unit_price:listing.sale_price||listing.retail_price},{onConflict:"cart_id,variant_id"});setMessage(itemError?itemError.message:"已加入购物车");}
if(!listing)return <main className="shop-section"><EmptyState title="未找到商品" description="商品可能尚未上架或已经下架。"/></main>;const images=product.product_images??[];return <main className="shop-section"><div style={{display:"grid",gridTemplateColumns:"minmax(0,1.1fr) minmax(320px,.8fr)",gap:45}}><div className="product-grid" style={{gridTemplateColumns:"repeat(2,1fr)"}}>{images.length?images.map((img:any)=><div className="product-image" key={img.id}><img src={img.public_url} alt={listing.title}/></div>):<div className="product-image"><div className="product-placeholder">暂无图片</div></div>}</div><div><p className="eyebrow">{product.style_no}</p><h1 style={{fontSize:35,margin:"8px 0 12px"}}>{listing.title}</h1><div className="product-price" style={{fontSize:23}}>€ {Number(listing.sale_price||listing.retail_price).toFixed(2)}</div><p className="muted" style={{lineHeight:1.8,fontSize:13,margin:"24px 0"}}>{listing.short_description||product.description}</p><div className="field"><label>选择颜色与尺码</label><select value={selected?.id??""} onChange={e=>setVariantId(e.target.value)}>{variants.map((v:any)=><option value={v.id} key={v.id}>{v.colors?.name} · {v.sizes?.name} · 可售 {Math.min(Math.max(0,(v.inventory?.[0]?.quantity_on_hand??0)-(v.inventory?.[0]?.quantity_reserved??0)),v.inventory?.[0]?.online_quantity_limit??0)}</option>)}</select></div><div style={{display:"flex",alignItems:"center",gap:7,margin:"18px 0"}}><button className="icon-btn" onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={14}/></button><span style={{width:40,textAlign:"center"}}>{qty}</span><button className="icon-btn" onClick={()=>setQty(Math.min(available,qty+1))}><Plus size={14}/></button><span className="muted" style={{fontSize:11,marginLeft:7}}>{available>0?`现货 ${available} 件`:"暂时缺货"}</span></div>{message&&<div className="notice">{message}</div>}<button className="button primary" style={{width:"100%",minHeight:48}} disabled={!available} onClick={add}><ShoppingBag size={17}/>加入购物车</button><div style={{borderTop:"1px solid var(--line)",marginTop:28,paddingTop:22}}><strong style={{fontSize:13}}>商品详情</strong><p className="muted" style={{fontSize:12,lineHeight:1.8,whiteSpace:"pre-wrap"}}>{product.description}</p></div></div></div></main>}
