"use client";
import { useCallback, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, LoaderCircle, Minus, Plus } from "lucide-react";
import { PageHead } from "@/components/shared/page-head";
import { SetupBanner } from "@/components/shared/setup-banner";
import { useSupabaseQuery } from "@/hooks/use-supabase-query";
import { getSupabase } from "@/lib/supabase/client";
const EMPTY:any[]=[];
export default function Receive(){const {id}=useParams<{id:string}>();const query=useCallback((c:any)=>c.from("stock_receipt_items").select("id,normalized_style_no,normalized_color,normalized_size,expected_quantity,received_quantity").eq("receipt_id",id).order("raw_line_number"),[id]);const {data,refresh}=useSupabaseQuery<any[]>(query,EMPTY);const [values,setValues]=useState<Record<string,number>>({});const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const value=(r:any)=>values[r.id]??r.received_quantity??0;const set=(r:any,n:number)=>setValues(v=>({...v,[r.id]:Math.max(0,n)}));async function save(){const client=getSupabase();if(!client)return;setSaving(true);for(const r of data){const received=value(r);const {error}=await client.from("stock_receipt_items").update({received_quantity:received,difference_quantity:received-r.expected_quantity,status:"RECEIVED"}).eq("id",r.id);if(error){setMessage(error.message);setSaving(false);return;}}await client.from("stock_receipts").update({received_quantity:data.reduce((a,r)=>a+value(r),0),status:"READY_TO_CONFIRM"}).eq("id",id);setMessage("实收数量已保存。");setSaving(false);await refresh();}
return <main className="page"><PageHead eyebrow="RECEIVING" title="实收数量核对" subtitle="按实际到货逐项录入，差异会被完整保留。" action={<Link className="button" href={`/warehouse/receipts/${id}/parse`}><ArrowLeft size={15}/>返回解析结果</Link>}/><SetupBanner/><div className="progress-line"><span className="progress-step done"><i>✓</i>导入货单</span><span className="progress-rule"/><span className="progress-step done"><i>✓</i>解析检查</span><span className="progress-rule"/><span className="progress-step active"><i>3</i>实收核对</span><span className="progress-rule"/><span className="progress-step"><i>4</i>确认入库</span></div><section className="panel"><div className="panel-head"><div><h2>到货明细</h2><p>可一键按货单数量确认，再调整差异行</p></div><button className="button small panel-action" onClick={()=>setValues(Object.fromEntries(data.map(r=>[r.id,r.expected_quantity])))}><Check size={14}/>全部与货单一致</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>款号</th><th>颜色</th><th>尺码</th><th>货单数量</th><th>实收数量</th><th>差异</th><th>状态</th></tr></thead><tbody>{data.map(r=>{const diff=value(r)-r.expected_quantity;return <tr key={r.id}><td><strong>{r.normalized_style_no}</strong></td><td>{r.normalized_color}</td><td>{r.normalized_size}</td><td>{r.expected_quantity}</td><td><div style={{display:"flex",alignItems:"center",gap:6}}><button className="icon-btn" onClick={()=>set(r,value(r)-1)}><Minus size={13}/></button><input className="table-input" style={{width:75,textAlign:"center"}} type="number" min="0" value={value(r)} onChange={e=>set(r,Number(e.target.value))}/><button className="icon-btn" onClick={()=>set(r,value(r)+1)}><Plus size={13}/></button></div></td><td style={{color:diff===0?"var(--brand)":diff<0?"var(--danger)":"var(--warning)",fontWeight:700}}>{diff>0?`+${diff}`:diff}</td><td>{value(r)===0?"未核对":diff===0?"一致":diff<0?"少货":"多货"}</td></tr>})}</tbody></table></div><div className="form-actions" style={{padding:18}}>{message&&<span className="muted" style={{marginRight:"auto",fontSize:11}}>{message}</span>}<button className="button" disabled={saving} onClick={save}>{saving&&<LoaderCircle size={15}/>}保存核对</button><Link className="button primary" href={`/warehouse/receipts/${id}/confirm`}>进入确认入库 <ArrowRight size={15}/></Link></div></section></main>}
