"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, FileSpreadsheet, ImagePlus, LoaderCircle, Plus, WandSparkles } from "lucide-react";
import Link from "next/link";
import { PageHead } from "@/components/shared/page-head";
import { SetupBanner } from "@/components/shared/setup-banner";
import { StatusBadge } from "@/components/shared/status-badge";
import { getSupabase } from "@/lib/supabase/client";
import { mergeDuplicateItems, parseReceiptText, type ParsedReceiptItem } from "@/lib/parser/receipt-parser";

const EXAMPLE="1.DL30283 18棕 18黑\n2.BL30385 100黑 41棕 51红 29绿\n3.Z2690 浅牛12S9M5L 深牛12S13M6L";
type Option={id:string;name:string};

export default function NewReceipt(){
 const router=useRouter();const [tab,setTab]=useState("text");const [source,setSource]=useState("");const [items,setItems]=useState<ParsedReceiptItem[]>([]);const [suppliers,setSuppliers]=useState<Option[]>([]);const [warehouses,setWarehouses]=useState<Option[]>([]);const [supplierId,setSupplierId]=useState("");const [warehouseId,setWarehouseId]=useState("");const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [notes,setNotes]=useState("");const [saving,setSaving]=useState(false);const [message,setMessage]=useState<string|null>(null);
 useEffect(()=>{const client=getSupabase();if(!client)return;void Promise.all([client.from("suppliers").select("id,name").is("deleted_at",null).order("name"),client.from("warehouses").select("id,name").eq("is_active",true).order("name")]).then(([s,w])=>{setSuppliers(s.data??[]);setWarehouses(w.data??[]);if(w.data?.[0])setWarehouseId(w.data[0].id);});},[]);
 const summary=useMemo(()=>({styles:new Set(items.map(i=>i.normalizedStyleNo)).size,skus:items.length,total:items.reduce((a,i)=>a+(i.quantity??0),0),errors:items.filter(i=>i.status==="ERROR").length,duplicates:items.filter(i=>i.duplicateKey).length}),[items]);
 function parse(){setMessage(null);if(!source.trim()){setMessage("请先粘贴供应商货单文字。");return;}setItems(parseReceiptText(source));}
 function update(index:number,key:keyof ParsedReceiptItem,value:string|number){setItems(current=>current.map((item,i)=>i===index?{...item,[key]:value}:item));}
 async function save(){const client=getSupabase();if(!client){setMessage("请先配置 Supabase 环境变量。");return;}if(!warehouseId){setMessage("请选择仓库。");return;}if(!items.length){setMessage("请先解析货单。");return;}if(items.some(i=>i.status==="ERROR"||!i.quantity)){setMessage("仍有错误记录，修正后才能保存入库单。");return;}setSaving(true);setMessage(null);const {data:user}=await client.auth.getUser();if(!user.user){setMessage("请先登录员工账号。");setSaving(false);return;}const {data:receipt,error}=await client.from("stock_receipts").insert({receipt_date:date,supplier_id:supplierId||null,warehouse_id:warehouseId,source_type:"PASTED_TEXT",status:items.some(i=>i.duplicateKey)?"PENDING_REVIEW":"RECEIVING",expected_quantity:summary.total,received_quantity:0,exception_count:items.filter(i=>i.status!=="VALID").length,notes,created_by:user.user.id}).select("id").single();if(error||!receipt){setMessage(error?.message??"创建入库单失败，库存未发生变化。");setSaving(false);return;}const rawLines=source.split(/\r?\n/).filter(Boolean).map((raw_text,line)=>({receipt_id:receipt.id,line_number:line+1,raw_text,parse_status:"PARSED"}));const dbItems=items.map(i=>({receipt_id:receipt.id,raw_line_number:i.lineNumber,raw_style_no:i.rawStyleNo,normalized_style_no:i.normalizedStyleNo,raw_color:i.rawColor,normalized_color:i.normalizedColor,raw_size:i.rawSize,normalized_size:i.normalizedSize,expected_quantity:i.quantity,received_quantity:null,difference_quantity:null,status:i.status==="ERROR"?"ERROR":"PENDING",notes:i.error}));const [{error:rawError},{error:itemError}]=await Promise.all([client.from("stock_receipt_raw_lines").insert(rawLines),client.from("stock_receipt_items").insert(dbItems)]);if(rawError||itemError){setMessage(rawError?.message??itemError?.message??"保存解析结果失败");setSaving(false);return;}router.push(`/warehouse/receipts/${receipt.id}/parse`);}
 return <main className="page"><PageHead eyebrow="NEW STOCK RECEIPT" title="新建入库单" subtitle="先填写基础信息，再导入供应商货单并检查解析结果。" action={<Link className="button" href="/warehouse"><ArrowLeft size={15}/>返回首页</Link>}/><SetupBanner/>
 <div className="progress-line"><span className="progress-step active"><i>1</i>导入货单</span><span className="progress-rule"/><span className="progress-step"><i>2</i>解析检查</span><span className="progress-rule"/><span className="progress-step"><i>3</i>实收核对</span><span className="progress-rule"/><span className="progress-step"><i>4</i>确认入库</span></div>
 <section className="form-card"><div className="form-grid"><div className="field"><label>入库日期 *</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>仓库 *</label><select value={warehouseId} onChange={e=>setWarehouseId(e.target.value)}><option value="">请选择仓库</option>{warehouses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="field"><label>供应商</label><select value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">未指定</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="field"><label>备注</label><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="货运单号、箱数或其他说明"/></div></div></section>
 <section className="form-card" style={{marginTop:16}}><div className="tabs"><button className={`tab ${tab==="text"?"active":""}`} onClick={()=>setTab("text")}><WandSparkles size={14}/> 粘贴文字</button><button className={`tab ${tab==="excel"?"active":""}`} onClick={()=>setTab("excel")}><FileSpreadsheet size={14}/> Excel / CSV</button><button className={`tab ${tab==="manual"?"active":""}`} onClick={()=>setTab("manual")}><Plus size={14}/> 手动添加</button><button className={`tab ${tab==="ocr"?"active":""}`} onClick={()=>setTab("ocr")}><ImagePlus size={14}/> 拍照识别</button></div>
 {tab==="text"&&<><div className="field full"><label>供应商货单文字</label><textarea value={source} onChange={e=>setSource(e.target.value)} placeholder={EXAMPLE}/><div className="field-help">支持“18棕”“浅牛12S9M5L”等紧凑格式；系统保留每一行原文便于追溯。</div></div><div className="form-actions"><button className="button" onClick={()=>setSource(EXAMPLE)}>填入格式示例</button><button className="button primary" onClick={parse}><WandSparkles size={16}/>开始解析</button></div></>}
 {tab==="excel"&&<div className="empty"><div><div className="empty-icon"><FileSpreadsheet/></div><b>Excel / CSV 导入接口已预留</b><span>字段规范与校验规则已写入 README，下一阶段接入文件解析。</span></div></div>}{tab==="manual"&&<div className="empty"><div><b>请先使用文字模式</b><span>解析后可在下方逐行编辑，也可以添加或删除记录。</span></div></div>}{tab==="ocr"&&<div className="empty"><div><div className="empty-icon"><ImagePlus/></div><b>拍照识别将在后续版本开放</b><span>V1.0 先保障文字和结构化导入的库存准确性。</span></div></div>}</section>
 {items.length>0&&<section className="panel" style={{marginTop:16}}><div className="panel-head"><div><h2>解析预览</h2><p>保存前请确认颜色、尺码与数量</p></div>{summary.duplicates>0&&<button className="button small panel-action" onClick={()=>setItems(mergeDuplicateItems(items))}>合并重复项</button>}</div><div className="panel-body"><div className="parse-summary"><div className="mini-stat"><span>款号</span><b>{summary.styles}</b></div><div className="mini-stat"><span>SKU</span><b>{summary.skus}</b></div><div className="mini-stat"><span>总件数</span><b>{summary.total}</b></div><div className="mini-stat"><span>错误</span><b>{summary.errors}</b></div><div className="mini-stat"><span>重复</span><b>{summary.duplicates}</b></div></div>{summary.duplicates>0&&<div className="notice warning">发现同款同色同码重复记录。系统不会静默合并，请点击“合并重复项”或保留并继续人工确认。</div>}<div className="table-wrap"><table className="data-table"><thead><tr><th>行</th><th>款号</th><th>颜色</th><th>尺码</th><th>数量</th><th>状态</th><th>提示</th></tr></thead><tbody>{items.map((item,index)=><tr key={`${item.lineNumber}-${index}`}><td>{item.lineNumber}</td><td><input className="table-input" value={item.normalizedStyleNo} onChange={e=>update(index,"normalizedStyleNo",e.target.value)}/></td><td><input className="table-input" value={item.normalizedColor} onChange={e=>update(index,"normalizedColor",e.target.value)}/></td><td><input className="table-input" value={item.normalizedSize} onChange={e=>update(index,"normalizedSize",e.target.value)}/></td><td><input className="table-input" style={{width:80}} type="number" min="1" value={item.quantity??""} onChange={e=>update(index,"quantity",Number(e.target.value))}/></td><td><StatusBadge value={item.status}/></td><td className="muted">{item.error??"—"}</td></tr>)}</tbody></table></div></div><div className="form-actions" style={{padding:"0 18px 18px"}}>{message&&<span style={{color:"var(--danger)",fontSize:12,marginRight:"auto"}}>{message}</span>}<button className="button primary" disabled={saving} onClick={save}>{saving?<LoaderCircle className="animate-spin" size={16}/>:null}{saving?"保存中…":"保存并继续核对"}</button></div></section>}
 </main>;
}
